CONFIG_EMAIL_HOST = 'smtp_server'
CONFIG_EMAIL_PORT = 465
CONFIG_EMAIL_HOST_USER = 'email'
CONFIG_EMAIL_HOST_PASSWORD = 'password'

CONFIG_NAME = 'collections'
CONFIG_USER = 'user'
CONFIG_PASSWORD = 'password'
CONFIG_HOST = 'localhost'
CONFIG_PORT = '5432'
