# Generated by Django 4.0.3 on 2022-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_card_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardentry',
            name='acquired',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
