# Generated by Django 4.0.3 on 2022-04-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_dust'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='craft_cost',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='turn_to_dust_value',
            field=models.IntegerField(default=10),
        ),
    ]
