# Generated by Django 4.0.3 on 2022-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_card_craft_cost_card_rarity_card_turn_to_dust_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_grayscaled',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
