# Generated by Django 4.0.3 on 2022-04-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_card_image_grayscaled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='collection',
            name='short_description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
