# Generated by Django 4.0.3 on 2022-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_description_collection_long_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='collection',
            name='image2',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='image3',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
