# Generated by Django 4.0.3 on 2022-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_image_collection_image1_collection_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image2',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image3',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
